import { DisclaimerBanner } from '../components/Disclaimer';

export default function Disclaimer() {
  return (
    <div className="page disclaimer-page">
      <DisclaimerBanner />
      <h1>Disclaimer</h1>

      <section aria-labelledby="general-heading">
        <h2 id="general-heading">General Disclaimer</h2>
        <p>
          PlanVocate is an educational tool created by Axiom 38 LLC, a Michigan limited liability
          company. The information provided through this website, including the eligibility screener,
          learning center, and meeting preparation guides, is for general educational and
          informational purposes only.
        </p>
      </section>

      <section aria-labelledby="legal-heading">
        <h2 id="legal-heading">Not Legal Advice</h2>
        <p>
          The content on this site does not constitute legal advice and does not create an
          attorney-client relationship between you and Axiom 38 LLC, PlanVocate, or any of its
          owners, employees, or affiliates. The information presented should not be relied upon as a
          substitute for professional legal counsel.
        </p>
        <p>
          Special education law — including the Individuals with Disabilities Education Act (IDEA,
          20 U.S.C. § 1400 et seq.) and Section 504 of the Rehabilitation Act (29 U.S.C. § 794) — is
          complex and varies by state and school district. Laws, regulations, and policies are subject
          to change. Always consult a licensed attorney or qualified advocate for advice specific to
          your situation.
        </p>
      </section>

      <section aria-labelledby="accuracy-heading">
        <h2 id="accuracy-heading">Accuracy of Information</h2>
        <p>
          While we strive to provide accurate and current information based on federal statutes,
          regulations, and published guidance from the U.S. Department of Education, we make no
          warranties or representations as to the accuracy, completeness, or timeliness of the
          content. Laws and regulations are updated regularly, and local implementation may differ
          from federal requirements.
        </p>
        <p>
          All legal citations reference real statutes, regulatory provisions, and published guidance
          documents. We do not fabricate citations. However, the application of these laws to your
          specific circumstances may differ. Verify current requirements with your state&apos;s
          Department of Education.
        </p>
      </section>

      <section aria-labelledby="guide-heading">
        <h2 id="guide-heading">Meeting Preparation Guides</h2>
        <p>
          The meeting preparation guides generated by PlanVocate are educational tools designed to
          help parents and educators prepare for IEP and 504 meetings. These guides:
        </p>
        <ul>
          <li>Are generated entirely in your browser — no child data is sent to our servers</li>
          <li>Are based on general federal and state law as of the date of generation</li>
          <li>Do not account for your specific circumstances, recent legal changes, or local policies</li>
          <li>Should not be presented as legal authority in meetings or proceedings</li>
          <li>Are not a substitute for consultation with a licensed attorney or qualified advocate</li>
        </ul>
      </section>

      <section aria-labelledby="screener-heading">
        <h2 id="screener-heading">Eligibility Screener</h2>
        <p>
          The free eligibility screener provides general guidance about whether an IEP or 504 plan
          may be appropriate based on your responses. It is not a diagnostic tool and does not
          determine eligibility. Only a qualified team of professionals can make eligibility
          determinations in accordance with IDEA (34 CFR §300.306) or Section 504 (34 CFR §104.35).
        </p>
      </section>

      <section aria-labelledby="privacy-heading">
        <h2 id="privacy-heading">Privacy</h2>
        <p>
          We take your privacy seriously. See our <a href="/privacy">Privacy Policy</a> for details
          on what information we collect and how it is used. No information about your child is ever
          stored on our servers.
        </p>
      </section>

      <section aria-labelledby="liability-heading">
        <h2 id="liability-heading">Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, Axiom 38 LLC and its owners, employees, and
          affiliates shall not be liable for any direct, indirect, incidental, consequential, or
          punitive damages arising from your use of PlanVocate, reliance on the information provided,
          or any actions taken based on the content of this site or generated guides.
        </p>
      </section>

      <section aria-labelledby="contact-heading">
        <h2 id="contact-heading">Contact</h2>
        <p>
          If you have questions about this disclaimer or PlanVocate, contact us at{' '}
          <a href="mailto:support@planvocate.com">support@planvocate.com</a>.
        </p>
        <p>
          Axiom 38 LLC | Michigan
        </p>
      </section>
    </div>
  );
}
